---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
infant <- rio::import("https://github.com/Fundamentals-Surya/hw4/raw/refs/heads/main/infant_subset.csv") # Import the cleaned and formatted table for infant mortality rate
life <- rio::import("https://github.com/Fundamentals-Surya/hw4/raw/refs/heads/main/life_subset.csv") # Import the cleaned and formatted table for life expectancy average
maternal <- rio::import("https://github.com/Fundamentals-Surya/hw4/raw/refs/heads/main/maternal_subset.csv") # Import the cleaned and formatted table for maternal mortality rate

folder <- "csvs" # Creates folder name string
if (!dir.exists(folder)) dir.create(folder) # Creates new directory if it does not exist

```

```{r}
merged_temp <- merge(infant, life, by=c("Country", "Region"), all=TRUE) # Merge the Infant table and Life table by using Country and Region as key, while including all rows from both tables
final_data <- merge(merged_temp, maternal, by=c("Country", "Region"), all=TRUE) # Merge the table above and Maternal table by using Country and Region as key, while including all rows from both tables
rio::export(final_data, "csvs/cia_merge.csv") # Export the merged table as a csv file

```

```{r}
print(paste("Total Rows:", nrow(final_data))) # Outputs the number of rows of merged table
print(paste("Total Columns:", ncol(final_data))) # Outputs the number of columns of merged table

names(final_data) # Outputs the column names of the table

# head(final_data) # Displays the first rows of the table

colSums(is.na(final_data)) # Outputs out number of missing values per column

file.exists("csvs/cia_merge.csv") # Checks if merged csv file was exported and saved correctly

```

```{r}
cia_data <- rio::import("csvs/cia_merge.csv") # Import the previous merged csv as a data frame
cia_aggregated <- aggregate(cbind(DeathsPer1000, Years, DeathsPer100_000) ~ Region, 
                            data = cia_data, 
                            FUN = mean, 
                            na.rm = TRUE) # Aggregates the table by region and averages the three variables per region and creates new table from that
rio::export(cia_aggregated, "csvs/cia_aggregated.csv") # Export the aggregated table as a csv file

```

```{r}
# head(cia_aggregated) # Displays the first rows of the table

str(cia_aggregated) # Verify the data, data types, structure, and col names of the table
 
length(unique(cia_data$Region)) == nrow(cia_aggregated) # Ensures that the number of regions from the original table match the aggregated table's number of regions

file.exists("csvs/cia_aggregated.csv") # Checks if aggretgated csv file was exported and saved correctly

```

```{r}
cia_wide <- rio::import("csvs/cia_merge.csv") # Imports merged csv as a dataframe

cia_long <- reshape(cia_wide, 
                    direction = "long",
                    varying = c("DeathsPer1000", "Years", "DeathsPer100_000"),
                    v.names = "Value",
                    timevar = "Indicator",
                    times = c("InfantMortality", "LifeExpectancy", "MaternalMortality"),
                    idvar = c("Country", "Region")) # Converts the wide table into long table format, turns the three vars into one categorical column, making a 4 column table

cia_long$Region <- NULL # Removes the region column

rio::export(cia_long, "csvs/cia_long.csv") # Export the long table as a csv file

```

```{r}
print(paste("Wide rows:", nrow(cia_wide))) # Outputs the number of rows in wide table
print(paste("Long rows:", nrow(cia_long))) # Outputs the number of rows in long table

#head(cia_long) # Displays the first rows of the table

names(cia_long) # Prints column names of long tablex

unique(cia_long$Indicator) # Outputs the unique values of the indicator column

file.exists("csvs/cia_long.csv") # Checks if long csv file was exported and saved correctly

```

